dataset: ./dataset/coco_train_singlelabel.txt
data: /data/chenhui/wangao/datasets/coco2014
lr: 1e-4
model_name: resnet50
num_classes: 80
workers: 16
thre: 0.5
batch_size: 128
loss: SPLC
log_file: train.txt
epochs: 60
total_epochs: 80
weight_decay: 1e-4
checkpoint: base
test: false
